### ISSUE TITLE
[ENHANCEMENT] Better the lighthouse score in mobile device

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#113]
### Description

This issue is raised to increase the lighthouse score in the mobile device.
<img width="658" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/3708a8d5-b80d-4646-bf5f-2466d75cd5b6">

### Current Behavior

Currently we have average of 80, we need to get it to 100% like desktop version

### Proposed Enhancement

Solve all the recommended issues by the lighthouse team

### Use Case

This will enhance the performance of the project

**Comment by jjinendra3** [comment]
Hey Krishna, just checked the Mobile Lighthouse scores, and it seems that the project uses fontawesome icons according to LightHouse Treemap, removing/replacing fontawesome would significantly improve the performance (atleast the LCP), so i'd recommend doing that, rest things can are pretty standard, like adding name attribute to buttons and alt attributes to Images which will take Accesibilty and SEO to 100. Hope it helps :)

**Comment by krishnaacharyaa** [comment]
Hey sure @jjinendra3 thank for taking out time for this issue, would you wanna take this up? Else this comment can be used by anyone who wants to take this issue, if you are currently occupied :)

**Comment by jjinendra3** [comment]
:( Unfortunately, would not be able to take it up due to some commitments till 7th of April but would love to take it up if its still available to take up post 7th Apr :)

**Comment by jjinendra3** [comment]
You can assign this to me :)

**Comment by krishnaacharyaa** [comment]
Sure @jjinendra3, Need your help in the auth if possible, post that we can take this up

**Comment by jjinendra3** [comment]
> Sure @jjinendra3, Need your help in the auth if possible, post that we can take this up

Could you mention the issue number please

**Comment by krishnaacharyaa** [comment]
@jjinendra3 it is mostly being discussed in the discord, https://github.com/krishnaacharyaa/wanderlust/issues/37 this is the issue, you might not find any info in the issue description, You can see in the PR , there is a related PR raised... And discord for more better understanding

**Comment by jjinendra3** [comment]
So, I've addressed the accessibility and SEO issues, and achieved scores of 95-100. However, performance remains a concern. On mobile, images load fully before resizing to fit the viewport, leading to longer load times compared to the desktop version where resizing is minimal. To tackle this, we could manually create multiple image sizes (ranging from 360px to 4k) in the project directory, or consider using online services like [Twicpics](https://www.twicpics.com/) or ImageOptim. However, I believe both of these approaches might be beyond the project scope since the current mobile performance is acceptable. Please LMK your thoughts on this!

**Comment by krishnaacharyaa** [comment]
Now what is the performance, can you share the image, Or better can you raise the PR, we'll see what's the updated value in the vercel host @jjinendra3
