### ISSUE TITLE
Decreasing the loading time of the application

### ISSUE THREAD

**Issue by krishnaacharyaa** [krishnaacharyaa/wanderlust#12]
According to lighthouse
Desktop:
![image](https://github.com/krishnaacharyaa/wanderlust/assets/116620586/be443a81-7d0d-4e75-8eed-36533aa031a0)

Mobile
![image](https://github.com/krishnaacharyaa/wanderlust/assets/116620586/bac0758c-ee11-4df8-a6aa-b170d0dd8e95)

Presently in lighthouse the performance we have it around 60 and 42 which is really poor, we have to aim to get it more than 95%

**Comment by krishnaacharyaa** [comment]
Hi @jjinendra3, can you kindly take up this issue, you might have to explore some parts but I guess it will be easy for you,
let me know your thoughts on this

**Comment by jjinendra3** [comment]
Hey @krishnaacharyaa , sure, i will try my best for the same, please assign it to me :)

**Comment by krishnaacharyaa** [comment]
Hey @jjinendra3, can you please consider converting all the jpg in the sample database to webP format? That would also add up in the boosting of performance ofcourse and for the future we'll anyway have a drop a file option for images there we can optimize once it is stored in platforms like cloudinary or so.

If you feel it can be covered in this story we'll do it here, if you feel it requires dedicated time, we can create a enhancement issue for that :)

**Comment by jjinendra3** [comment]
> Hey @jjinendra3, can you please consider converting all the jpg in the sample database to webP format? That would also add up in the boosting of performance ofcourse and for the future we'll anyway have a drop a file option for images there we can optimize once it is stored in platforms like cloudinary or so.
> 
> If you feel it can be covered in this story we'll do it here, if you feel it requires dedicated time, we can create a enhancement issue for that :)

Yeah i figured this out yesterday night that the images are the ones taking too much time hence lowering the performance, the webp bg has also increased the performance score in lighthouse as compared to 60 & 42, i will convert all of them to webp files, no issues, no need to create a different issue for that, but thinking a permanent solution so that whenever the user adds images, no issue comes up is integral .

**Comment by krishnaacharyaa** [comment]
Yeah for that, may be for now we can allow users to just add in form of webP images, in long run I have planned we will give them opportunity to upload images and we can deploy it elsewhere and decide the format in which it is stored, and also consider coversion of image types if needed in the backend.

**Comment by jjinendra3** [comment]
The image conversion did have an impact, but the performance is still not up to the mark (~80), primarily due to a high Longest Contentful Paint (LCP) score. There are two main reasons for this: React Router DOM and React Icons.

React Router DOM is an essential library for the website and cannot be removed. I'm confident that the build will have more efficient DOM usage compared to the localhost.

As for the issue with React Icons, I suggest removing the package and replacing it with a CDN like FontAwesome. Although there are some associated issues with FontAwesome, it should significantly improve the performance.

Please let me know the steps I should follow next. 

P.S. The suggested updates will result in a higher score on Lighthouse. In reality, the webpage now loads almost instantaneously after the WebP conversion update.

**Comment by jjinendra3** [comment]
Also , i have added a package called compression in the backend which compresses the html css js to gzip format which has also contributed in faster FCP (First Contentful Paint).

**Comment by krishnaacharyaa** [comment]
Thank you for your detailed research efforts and time, much appreciated. Sure sounds great, can you consider changing the react icons with fontawesome ? and about react router is there any type of optimization that we can do? could you explore a little on that.

May be after fontawesome conversion, raise a PR, I'll remove the authorization part of deployment so you dont have to wait for my approval for the build every time you change, so you can get proper estimate in the runtime. 
However the vercel server may be slow and we cannot do anything about that, one resolution would be purchasing a server and deploying, which presently is not at scope, the most we can do is presently to have the ideal lighthouse score that should do :)

**Comment by jjinendra3** [comment]
> Thank you for your detailed research efforts and time, much appreciated. Sure sounds great, can you consider changing the react icons with fontawesome ? and about react router is there any type of optimization that we can do? could you explore a little on that.
> 
> May be after fontawesome conversion, raise a PR, I'll remove the authorization part of deployment so you dont have to wait for my approval for the build every time you change, so you can get proper estimate in the runtime. 
> However the vercel server may be slow and we cannot do anything about that, one resolution would be subscribing to a aws server and deploying, which presently is not at scope, the most we can do is presently to have the best lighthouse score. That should do :)

Got it, on it!👍

**Comment by jjinendra3** [comment]
Found an alternative to react-router-dom named Wouter which was actually created to specifically tackle this performance issue, it has all the main features of router-dom, i would recommend you go through a blog on it [Wouter](https://www.habilelabs.io/blog/wouter-a-minimalist-alternative-to-react-router)

**Comment by krishnaacharyaa** [comment]
Seems like the closes issue number we missed the pattern so it is not auto closed, for now linking manually, please look into this next time and let me know if some changes is required in the PR template 
<img width="348" alt="image" src="https://github.com/krishnaacharyaa/wanderlust/assets/116620586/737aece8-633d-485e-aa90-bc27aa6da774">

**Comment by krishnaacharyaa** [comment]
Closing as resolved
