### ISSUE TITLE
Make Navbar Sticky While Scrolling

### ISSUE THREAD

**Issue by krishnas005** [krishnaacharyaa/wanderlust#182]
### Description

I'd like to propose an enhancement to make the Navbar sticky while scrolling. This would improve the user experience by keeping navigation options readily accessible even as users scroll down through the content.

### Current Behavior

At present, the Navbar scrolls out of view when users navigate down a long page. This can make it difficult for users to access navigation options without having to scroll back to the top.

### Proposed Enhancement

The Navbar would remain fixed at the top of the screen while users scroll through content. This would ensure that navigation options are always visible, allowing for quicker and more intuitive navigation within the site.

### Use Case

With a sticky Navbar, users can easily switch between sections without needing to scroll back to the top.

**Comment by krishnas005** [comment]
@krishnaacharyaa Please assign me this issue under GSSOC'24

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by reshamsai150** [comment]
navbar should be sticky  and i think improvement is needed in navbar section so please assign this issue to me

**Comment by krishnaacharyaa** [comment]
@reshamsai150 @krishnas005  Kindly find the code-of-conduct of the project [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share).
And if you feel this issue is not following the code-of-conduct. Kindly close the issue.
Looking forward to have you as a contributor in the project :) We have a long way to go

p.s: Feel free to join our discord server: https://discord.gg/FEKasAdCrG and assign roles for yourself in the group, The likely-hood of contributing in the project will be really high :)

**Comment by krishnaacharyaa** [comment]
And we have high priority task than this, no offence. But not the functionality presently needed. Thanks @krishnas005
