### ISSUE TITLE
[BUG]: On clicking on the sign in with google, the authentication window of google should open

### ISSUE THREAD

**Issue by mohit-bhandari45** [krishnaacharyaa/wanderlust#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current behaviour is that, on clicking it is navigating to the auth page

### Expected Behavior

A new window should open of google signup

### Reproduction steps

```bash
1. Go to Landing Page
2. Click on Log in
3. Click on sign in with google
4. See there is no action
```

### Screenshots

This window should open:-
![image](https://github.com/krishnaacharyaa/wanderlust/assets/151373021/6e3e7ced-7d61-42b5-b58c-2bf89c8f77be)

**Comment by mohit-bhandari45** [comment]
I want to work on this issue, please assign me

**Comment by ShristiSharan** [comment]
I have setup the environment and got the issue, 
@krishnaacharyaa please assign this Bug to me.

**Comment by krishnaacharyaa** [comment]
@ShristiSharan @mohit-bhandari45 Kindly find the code-of-conduct of the project [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share).
And if you feel this issue is not following the code-of-conduct. Kindly close the issue.
Looking forward to have you as a contributor in the project :) We have a long way to go

p.s: Feel free to join our discord server: https://discord.gg/FEKasAdCrG and assign roles for yourself in the group, The likely-hood of contributing in the project will be really high :)

**Comment by vamsidhar-914** [comment]
hey,I know the fix for the issue.can add google and github authentication.can you assign it to me

**Comment by iamrudhresh** [comment]
I hope you're doing great! As a GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you please assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!
