### ISSUE TITLE
[FEATURE] Invite Functionality for Others.

### ISSUE THREAD

**Issue by prafulnigam** [krishnaacharyaa/wanderlust#185]
A link would be generated to invite others to the platform.

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by krishnaacharyaa** [comment]
@prafulnigam  find the code-of-conduct of the project [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share).
And if you feel this issue is not following the code-of-conduct. Kindly close the issue.
Looking forward to have you as a contributor in the project :) We have a long way to go

p.s: Feel free to join our discord server: https://discord.gg/FEKasAdCrG and assign roles for yourself in the group, The likely-hood of contributing in the project will be really high :)
