### ISSUE TITLE
[BUG] Error while Updating the Profile Picture.

### ISSUE THREAD

**Issue by prafulnigam** [krishnaacharyaa/wanderlust#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

One is Unable to change the profile, resulting in an error.

![image](https://github.com/krishnaacharyaa/wanderlust/assets/78497704/15458d9e-c37e-48e9-9696-290784a1d5e4)

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by KavyaBS123** [comment]
Hey @prafulnigam I am a GSSOC Contributor can you please label this issue as GSSOC and assign this issue to me I would love to work on it!

**Comment by krishnaacharyaa** [comment]
@KavyaBS123 @Sooraj002 @prafulnigam   Kindly find the code-of-conduct of the project [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share).
And if you feel this issue is not following the code-of-conduct. Kindly close the issue.
Looking forward to have you as a contributor in the project :) We have a long way to go

p.s: Feel free to join our discord server: https://discord.gg/FEKasAdCrG and assign roles for yourself in the group, The likely-hood of contributing in the project will be really high :)

**Comment by krishnaacharyaa** [comment]
And i really don't know which products user profile you are speaking about. 

Closing this as issue related to some other project 😁
