### ISSUE TITLE
[FEATURE] : Dark mode functionality

### ISSUE THREAD

**Issue by tusharyadav11** [krishnaacharyaa/wanderlust#189]
### Description

 want to work on the functionality of dark mode and light mode  under Gssoc'24 . Please assign it to me

### Use Case

Will improve the user interface

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by mohit-bhandari45** [comment]
I also want to work on this issue under gssoc24

**Comment by KavyaBS123** [comment]
Hey @Sooraj002 I am  a GSSOC contributor can you please label this issue as GSSOC  and assign this issue to me I would love to work on it!

**Comment by Sooraj002** [comment]
> Hey @Sooraj002 I am a GSSOC contributor can you please label this issue as GSSOC and assign this issue to me I would love to work on it!

Well, I am Also a Contributor . I think you should ask the admin @krishnaacharyaa

**Comment by krishnaacharyaa** [comment]
@Sooraj002 It is already there dear, the functionality :)

**Comment by krishnaacharyaa** [comment]
@Sooraj002 @KavyaBS123 @mohit-bhandari45 @tusharyadav11  Kindly find the code-of-conduct of the project [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share).
And if you feel this issue is not following the code-of-conduct. Kindly close the issue.
Looking forward to have you as a contributor in the project :) We have a long way to go

p.s: Feel free to join our discord server: https://discord.gg/FEKasAdCrG and assign roles for yourself in the group, The likely-hood of contributing in the project will be really high :)

**Comment by krishnaacharyaa** [comment]
Closing as it already exists
