### ISSUE TITLE
[FEATURE] Adding a newsletter section for engagment with users and collecting active users emails.

### ISSUE THREAD

**Issue by Adeesh-bode** [krishnaacharyaa/wanderlust#195]
### Description

The feature involves adding a newsletter section to a website or application to enhance engagement with users. This section typically allows users to subscribe to receive regular updates, news, promotions, or other relevant content via email. The primary purpose is to foster communication, keep users informed, and encourage repeat visits or interactions. Additionally, it involves collecting active users' email addresses for the purpose of sending newsletters.

### Use Case

Imagine a scenario where an e-commerce platform wants to increase customer engagement and retention. By adding a newsletter section, they can provide users with updates on new products, exclusive offers, and upcoming sales directly to their email inbox. Users who subscribe to the newsletter willingly provide their email addresses, indicating an interest in staying informed about the platform's offerings. This allows the platform to maintain a direct line of communication with its audience, resulting in increased brand loyalty, higher repeat purchases, and ultimately, improved revenue. Additionally, the collected email addresses can be utilized for targeted marketing campaigns, further enhancing the effectiveness of the platform's promotional efforts.

**Comment by krishnaacharyaa** [comment]
@Adeesh-bode Kindly find the code-of-conduct of the project [Code-of-conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3?origin=share).
And if you feel this issue is not following the code-of-conduct. Kindly close the issue.
Looking forward to have you as a contributor in the project :) We have a long way to go

p.s: Feel free to join our discord server: https://discord.gg/FEKasAdCrG and assign roles for yourself in the group, The likely-hood of contributing in the project will be really high :)

**Comment by krishnaacharyaa** [comment]
Closing as it violates [code of conduct](https://app.eraser.io/workspace/wQGMaE4BqFTVZ0tigke3)
