### ISSUE TITLE
[FEATURE] Adding scrollbar.

### ISSUE THREAD

**Issue by Mayur-666** [krishnaacharyaa/wanderlust#273]
### Description

Current scrollbar is browser default one.
I would like to add new scrollbar to the site.

### Use Case

Improves UI of the site.

### Proposed Solution

 Adding a scrollbar with sky blue or similar color that can match both the themes will look good on the site.

**Comment by Mayur-666** [comment]
Ss of current scrollbar :-

![Screenshot (559)](https://github.com/krishnaacharyaa/wanderlust/assets/118804110/0e7efb4f-69a2-40ec-a35f-f8063e87614e)

**Comment by krishnaacharyaa** [comment]
Looking forward to see it, but personally no interest, doesn't greatly impact the project directly. 

@Mayur-666 personal suggestion, you are great guy. Hunt for big sharks, leave all these UI related stuffs, we are now decent with UI, we need new things or enhacement in the existing things, get 3rd level tasks, which has big impact. 
That way both can be happy, it is good attention to details with these, but no use, because no real impact, what will you say in resume? I have changed scrollabar color in a Gssoc open source project? don't change the mindset, use yourself, you are underestimating yourself.
All the best

**Comment by Mayur-666** [comment]
See you in new issue.
