### ISSUE TITLE
[BUG] Image Zoom on Hover Causes Card Borders to Lose Rounded Corners

### ISSUE THREAD

**Issue by Vimall03** [krishnaacharyaa/wanderlust#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The image zooms in, but the card's rounded borders become square.

### Expected Behavior

The image should zoom in while maintaining the card's rounded borders.

### Reproduction steps

```bash
1. Hover over the card.
2. Observe the behavior of the image and the card's borders.
```

### Screenshots

https://github.com/krishnaacharyaa/wanderlust/assets/109758195/77bb505d-4b60-4cc9-8516-22a965bb00c9

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

**Comment by krishnaacharyaa** [comment]
Go ahead take it @Vimall03, follow contributing guidelines

**Comment by Vimall03** [comment]
@krishnaacharyaa can you assign me this issue under GSSoC'24, level 2

**Comment by krishnaacharyaa** [comment]
@Vimall03 https://github.com/krishnaacharyaa/wanderlust/pull/318 it is a simple readme, gave him 3rd level because almost a day there was back and forth about the requirements, in this actual PR #317 and he did it.

Simple take away don't ask me levels, just pure heart contributions, I'll give the highest possible out there, you come with this rounded thing and expect me to give 2nd level what is the whole point?
Actuall this is even not a bug, just because you wanted this points I'm go ahead do it... but tbh no respect, see the youtube and even they have the exact same bug, who cares dude!!!!!

Do something impactful, I feel you can do it, let me know if you wanna do something interesting and make a real impact :)
Happy to give you points even if you don't ask, 

And read the code of conduct, you'll get to know the mindset, once you know, I don't think any other project will give you this crazy points, I don't care much about points and stuff, i have had it enough! but i understand if you are hunting, but I know you know !! :)
All the best

**Comment by Vimall03** [comment]
Hi @krishnaacharyaa ,

Your response seemed unnecessarily harsh and off-topic. I was simply asking for a GSSOC label and a level, not to debate about the README file or any specific PR.

> This won't be given any level unfortunately. @Vimall03 I like the attention to detail. Read code of conduct for level 3 points

I completely agree with your previous reply, and it was more than enough for me to understand the situation. I never intended to force anything after that nor did I bring up some random PR for comparison.

I realize that asking for a level for a bug was not fair of me, and I'm sorry for that. However, saying "who cares dude" about a bug was dismissive and uncalled for.

Addressing even minor bugs is crucial for maintaining the project's quality and helps new contributors get familiar with the codebase. Let's aim to keep our interactions constructive and professional.

I just wanted to clarify that it's my way of getting started with the project. I often start with small bugs to get settled in before contributing more significantly. 

Given this interaction, I don't feel motivated to continue working on this project. Thanks for your time.

Regards,  
Vimall03

**Comment by krishnaacharyaa** [comment]
@Vimall03 good time spent on the reply, thanks for your time. I guess the "who cares dude!!!!"  is not taken as a scope of creating an actual impact rather as an insult, which is fine.

I wish you create an impact, thats all what I meant, you know it is my way of saying. You may find it unprofessional bla bla.
But I don't like being professional in chat and Hey bro person is chat for me, I am the same person and I don't switch roles.

You had a fair enough point of Thats how you work starting with chota bugs, that helps you get along with the project, makes sense. By reading the code of conduct of the project you should have ideally figured out the kinda person I am , and not get offended when i said it.

I felt you are a nice guy and a little push would actually help you, so spent some time on telling "create an impact" in the message nothing related to praising some other guy of readme. I never come back to issues once commented, but felt like doing anyways, turned out that it was offensive.

Take care :) Have a good contributing life !!

**Comment by krishnaacharyaa** [comment]
@Mayur-666 did you feel the same way? When i said focus on big things, create impact? like @Vimall03 felt? I just wanted to understand, if i am not able to properly convey the message altogether and being mean

**Comment by krishnaacharyaa** [comment]
Super @Mayur-666. That's great! 
I guess I was indeed harsh with @Vimall03 
Sorry mate if you felt offended.

Thank you 
All the best @Mayur-666. Rock it

**Comment by Vimall03** [comment]
Thanks for the masterclass in motivational chaos. Also, interesting move seeking validation. Thanks for the guidance!
