### ISSUE TITLE
[BUG] <View Password Icon Alignment Bug>

### ISSUE THREAD

**Issue by poseidonsanket** [krishnaacharyaa/wanderlust#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

View password alignment issues
![Screenshot (95)](https://github.com/krishnaacharyaa/wanderlust/assets/112609618/e99c8901-fff0-44f3-b90a-aeac4b9cebe9)

### Expected Behavior

It should be aligned properly in the password input tag

Can you assign me this issue under gssoc 2024

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)
![Screenshot (95)](https://github.com/krishnaacharyaa/wanderlust/assets/112609618/8bf8843e-537f-4052-983c-e7561091d229)

### OS

Windows

**Comment by poseidonsanket** [comment]
@krishnaacharyaa it happens after invalid password attempt

**Comment by vamsidhar-914** [comment]
it happens when invalid password is typed.its because the error message is present in the relative div which button icon is present.

so I fixed this issue

before -
![336401038-8bf8843e-537f-4052-983c-e7561091d229](https://github.com/krishnaacharyaa/wanderlust/assets/127492265/e1d03eef-1f6b-4eee-a1bb-3cfd6c5be583)

after -
![Screenshot (193)](https://github.com/krishnaacharyaa/wanderlust/assets/127492265/df3477e8-d31d-44a9-9a15-4f6a6c5499db)
